export const metadata = { title: "Terms of Service — Maya" };

export default function TermsPage() {
  return (
    <main className="legal-shell">
      <div className="legal-card">
        <a className="brand" href="/">
          Maya
        </a>
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: [DATE] — draft, not yet reviewed by a lawyer.</p>

        <p className="legal-disclaimer">
          This is a starting template, not legal advice. Have a lawyer review and localize it
          (especially the arbitration, liability, and governing-law sections) before you rely on
          it in production. Replace every [bracketed] placeholder with your real details.
        </p>

        <h2>1. Who we are</h2>
        <p>
          Maya (&quot;the Service&quot;) is operated by [Company Name] (&quot;we&quot;, &quot;us&quot;). These
          Terms govern your access to and use of the Service. By creating an account or using
          Maya, you agree to these Terms.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old to use Maya. By using the Service you confirm you
          meet this requirement. Maya is a fictional AI character; conversations are not a
          substitute for professional medical, psychological, or emotional care. If you are in
          crisis, please contact a licensed professional or local emergency services.
        </p>

        <h2>3. Your account</h2>
        <p>
          You&apos;re responsible for the accuracy of the information you provide and for keeping
          your password confidential. Notify us immediately at [support email] if you suspect
          unauthorized use of your account.
        </p>

        <h2>4. Subscriptions and billing</h2>
        <p>
          Paid plans are billed in advance on a recurring basis through our payment processor,
          Stripe. Subscriptions renew automatically until cancelled. You can cancel any time from
          your account page; cancellation takes effect at the end of the current billing period.
          We do not store your card details — Stripe handles all payment data.
        </p>

        <h2>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to generate illegal content, or content involving minors</li>
          <li>Attempt to extract, reverse-engineer, or abuse the underlying AI models</li>
          <li>Circumvent rate limits, usage caps, or authentication</li>
          <li>Use the Service to harass, defraud, or harm another person</li>
        </ul>
        <p>We may suspend or terminate accounts that violate this section.</p>

        <h2>6. AI-generated content</h2>
        <p>
          Maya&apos;s responses are generated by third-party AI models and may be inaccurate,
          unexpected, or in character as fiction. Nothing Maya says constitutes professional
          advice (medical, legal, financial, or otherwise).
        </p>

        <h2>7. Third-party services</h2>
        <p>
          Delivering Maya&apos;s voice and conversation requires sending your audio and text to
          third-party AI providers (currently Google Gemini, ElevenLabs, and/or Surplus
          Intelligence, depending on configuration) for processing. Their own terms and privacy
          policies also apply to that processing. See our <a href="/privacy">Privacy Policy</a>{" "}
          for details.
        </p>

        <h2>8. Termination</h2>
        <p>
          You may stop using the Service and delete your account at any time. We may suspend or
          terminate your access for violating these Terms or applicable law.
        </p>

        <h2>9. Disclaimer and limitation of liability</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum
          extent permitted by law, [Company Name] is not liable for indirect, incidental, or
          consequential damages arising from your use of the Service.
        </p>

        <h2>10. Changes</h2>
        <p>
          We may update these Terms from time to time. We&apos;ll post the updated version here with
          a new &quot;Last updated&quot; date. Continued use after a change means you accept the
          updated Terms.
        </p>

        <h2>11. Governing law</h2>
        <p>These Terms are governed by the laws of [Jurisdiction], without regard to conflict-of-law principles.</p>

        <h2>12. Contact</h2>
        <p>Questions about these Terms? Email [support email].</p>

        <p className="legal-switch">
          <a href="/privacy">Privacy Policy</a> · <a href="/">Back to Maya</a>
        </p>
      </div>
    </main>
  );
}
